### ISSUE TITLE
FR: flag strings.HasPrefix("const str", "other const str")

### ISSUE THREAD

**Issue by josharian** [dominikh/go-tools#1297]
This is a depressingly common bug for me: I enclose the variable name of the first argument to strings.HasPrefix (and friends) in quotes. It compiles, it looks vaguely right, it is totally not right.

**Comment by dgryski** [comment]
Semgrep check:

```
rules:
  - id: strings-hasprefix-constants
    patterns:
      - pattern: strings.HasPrefix("...", "...")
    message: "strings.HasPrefix with constant strings"
    languages: [go]
    severity: ERROR
```

produces

```
dgryski@beekin semgrep-go % /usr/local/bin/semgrep -f hasprefix.yml server/main.go
Scanning 1 file.

Findings:

  server/main.go
     strings-hasprefix-constants
        strings.HasPrefix with constant strings

         31┆ if strings.HasPrefix("foo", "bar") {
```
