### ISSUE TITLE
Documentation for GitLab CICD in the Continuous Integration page

### ISSUE THREAD

**Issue by marcottedan** [dominikh/go-tools#1352]
Hey guys, I love your work but it would be really helpful to have a sub-page for GitLab CICD. It's broadly use.

Currently there's only documentation for GitHub Action: https://staticcheck.io/docs/running-staticcheck/ci/

Thanks in advance

**Comment by marcottedan** [comment]
I crafted that out of some random google search:

``` 
stages:
  - validate

go:staticcheck:
  image: golang:latest
  stage: validate
  script:
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - $GOPATH/bin/staticcheck -checks all ./...
  allow_failure: true
```
