### ISSUE TITLE
Package loading time in Go 1.10.x

### ISSUE THREAD

**Issue by klauspost** [dominikh/go-tools#377]
I seem to have an interesting issue where running the checked is *extremely* slow and CPU is pegged at 100% on one core.

```
klaus@ubuntu:~/gopath/src/user/package$ staticcheck --debug.print-stats github.com/user/package/...
Package loading: 1h38m31.454171864s
SSA build: 21.67682346s
Other init work: 6.817053264s
Checker inits:
        gosimple: 5.939782ms
        staticcheck: 6.580565926s
        stylecheck: 3.011µs
        unused: 308ns

Jobs:
        SA1023: 605.955µs
        ST1008: 2.835215ms
        SA5007: 12.190218ms
        SA4019: 740.066374ms
        SA5000: 788.664339ms
        SA4016: 1.341984904s
        ST1001: 1.548734657s
        SA2002: 1.751419466s
        SA4012: 1.980239895s
        SA6001: 3.151521396s
        SA4013: 3.616790341s
        SA4002: 3.741031528s
        S1020: 4.209893928s
        SA1013: 4.7203341s
        SA3001: 4.757165187s
        SA5004: 4.79783047s
        S1023: 4.847563802s
        SA1010: 4.898477989s
        SA4001: 4.92993824s
        S1010: 5.170548174s
        SA5002: 5.191772116s
        ST1015: 5.227913934s
        SA4011: 5.260503075s
        S1000: 5.506765333s
        SA4010: 5.602958172s
        SA4015: 5.635165478s
        SA6003: 5.826837105s
        S1006: 6.026174231s
        S1029: 6.288058228s
        S1017: 6.521211728s
        S1005: 6.657113216s
        SA1003: 7.166001256s
        SA4008: 8.185722499s
        SA1020: 8.47647566s
        SA6002: 9.123205597s
        SA1017: 10.400495305s
        SA6000: 11.090975882s
        SA1025: 11.55688655s
        SA5005: 12.273645941s
        SA2000: 12.657624433s
        SA1007: 12.86456794s
        SA4006: 14.983973684s
        SA1021: 15.570106172s
        ST1006: 19.799175166s
        SA1018: 19.7997434s
        SA3000: 19.806420248s
        SA2003: 20.006151449s
        S1021: 20.17263736s
        SA1024: 20.319294594s
        SA1011: 20.714653373s
        SA5003: 22.834504023s
        SA1002: 23.611794013s
        S1018: 23.82204222s
        SA1014: 24.237042124s
        SA1000: 25.042900226s
        SA6005: 29.890880858s
        S1008: 30.267773032s
        S1004: 30.617342398s
        ST1016: 31.025323399s
        S1009: 31.761876835s
        ST1012: 32.49133553s
        S1011: 33.264634843s
        SA9004: 34.480512655s
        S1001: 35.164602355s
        S1019: 36.734606891s
        SA1008: 37.6376481s
        SA9001: 37.677980421s
        SA4004: 38.47965889s
        S1030: 39.069030457s
        S1012: 39.084799926s
        S1016: 39.434007962s
        SA5001: 39.451987822s
        S1031: 39.666953149s
        S1002: 40.197963098s
        ST1011: 40.207626479s
        SA2001: 40.388245786s
        SA1012: 40.413728705s
        SA1016: 40.58124205s
        S1003: 40.626086764s
        SA4003: 40.691722167s
        S1028: 40.739847559s
        S1025: 40.829009563s
        ST1003: 40.984717091s
        ST1013: 40.990694135s
        SA1019: 41.040898529s
        S1024: 41.081448598s
        SA4018: 41.093339685s
        SA9002: 41.156389751s
        SA4000: 41.299867621s
        SA4014: 41.333049609s
        SA1001: 41.433742272s
        SA1015: 41.439050706s
        SA1006: 41.534056007s
        SA1005: 41.571696853s
        SA1004: 41.742200385s
        S1032: 41.787982319s
        S1007: 41.80344573s
        SA9003: 41.851629245s
        ST1005: 42.379658152s
        ST1000: 42.523186901s
        SA4009: 42.574494452s
        SA4017: 43.139778791s
        U1000: 45.419632247s
        Total: 39m54.325734682s

klaus@ubuntu:~/gopath/src/honnef.co/go/tools$ git cat-file commit HEAD
tree 822824557d88c8751120de337fdc352f5d58d041
parent 17562b81b08373b3b11be787d2cf278102bce55d

klaus@ubuntu:~/gopath/src/honnef.co/go/tools$ go version
go version go1.10.4 linux/amd64
klaus@ubuntu:~/gopath/src/honnef.co/go/tools$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/klaus/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/klaus/gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build804420424=/tmp/go-build -gno-record-gcc-switches"
```

It seems the times in Jobs doesn't add up to the total, and obviously the 1½ hour loading time seems a bit much. It is a big package with lots of dependencies, but this does seem a bit excessive.

I restarted with `--debug.cpuprofile="profile.cpu"` to get a profile, but obviously it will take a while before the results are available.
