### ISSUE TITLE
staticcheck: invalid TOML doesn't produce an error

### ISSUE THREAD

**Issue by ainar-g** [dominikh/go-tools#428]
staticcheck.conf:

```toml
checks = ["all"]
initialisms = ["DB"]
http_status_code_white_list: [] # N.B. invalid, colon instead of equals sign.
```

main.go:

```go
package main

import "fmt"

func main() {
	DbFoo := "foo"
	fmt.Println(DbFoo)
}
```

If I launch `$ staticcheck .`, it doesn't print an error and exit, but simply ignores the configuration file and doesn't print the warnings about `Db`. If I fix the configuration file, it works fine. I think that this is a rather surprising behaviour.
