### ISSUE TITLE
Load "fail" settings from staticcheck.conf

### ISSUE THREAD

**Issue by ex-nerd** [dominikh/go-tools#523]
We have several checks we would like to report on, but do not wish to trigger a linter failure that would prevent our CI system from passing the build (e.g. `SA1019` because using deprecated code should be fine while we're in the process of deprecating it).

Rather than adding a bunch (well, 2) flags to my CI scripts, it would be nice to just add something like this to `staticcheck.conf`:

```toml
checks = [ .... ]
fail = [
	# Do not fail for using a deprecated function
	"-SA1019",
	# Do not fail just because someone used capital letters or punctuation
	"-ST1005",
]
```
